[workspace]
license = "MPL-2.0"
members = [
    "direct-composition",
    "examples",
    "webrender",
    "webrender_api",
    "wrench",
]

[profile.release]
debug = true
panic = "abort"

[replace]
"https://github.com/rust-lang/crates.io-index#serde_derive:1.0.66" = { git = "https://github.com/servo/serde", branch = "deserialize_from_enums8", feature = "deserialize_in_place" }
"https://github.com/gfx-rs/gfx.git#gfx-hal:0.1.0" = { git = "https://github.com/gfx-rs/gfx.git", rev="b91498e8aa074e9e1936ead9ada4dfc5b7b02a42" }
"https://github.com/gfx-rs/gfx.git#gfx-backend-vulkan:0.1.0" = { git = "https://github.com/gfx-rs/gfx.git", rev="b91498e8aa074e9e1936ead9ada4dfc5b7b02a42" }
"https://github.com/gfx-rs/gfx.git#gfx-backend-dx12:0.1.0" = { git = "https://github.com/gfx-rs/gfx.git", rev="b91498e8aa074e9e1936ead9ada4dfc5b7b02a42" }
"https://github.com/gfx-rs/gfx.git#gfx-backend-metal:0.1.0" = { git = "https://github.com/gfx-rs/gfx.git", rev="b91498e8aa074e9e1936ead9ada4dfc5b7b02a42" }
"https://github.com/gfx-rs/gfx.git#gfx-backend-empty:0.1.0" = { git = "https://github.com/gfx-rs/gfx.git", rev="b91498e8aa074e9e1936ead9ada4dfc5b7b02a42" }
